apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kubesphere-logging-system
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kubesphere-logging-system
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      namespace: kubesphere-logging-system
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.0
          imagePullPolicy: IfNotPresent
          env:
            - name: "CLUSTER_NAME"
              value: "escluster"
            - name: XPACK_SECURITY_ENABLED
              value: 'false'
            - name: XPACK_GRAPH_ENABLED
              value: 'false'
            - name: XPACK_ML_ENABLED
              value: 'false'
            - name: XPACK_REPORTING_ENABLED
              value: 'false'
            - name: ELASTICSEARCH_HOSTS
              #value: 'http://$(ELASTICSEARCH_SERVICE_HOST):$(ELASTICSEARCH_SERVICE_PORT)'
              value: 'http://elasticsearch:9200'
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 5601
              name: kibana
              protocol: TCP