apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  # the logging namespace
  - logging-namespace.yaml

  # fluent-bit service account with read-only cluster role (it can get, list and watch other pods in the namespace)
  - https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/fluent-bit-service-account.yaml
  - https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/fluent-bit-role-binding-1.22.yaml

  # this daemonset deploys a Fluent Bit pods per nodes in the namespace
  - https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/output/elasticsearch/fluent-bit-ds-minikube.yaml

  # provide default configuration fo Fluent Bit pods (ElasticSearch host and port passed through env vars)
  - https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/output/elasticsearch/fluent-bit-configmap.yaml

  # ElasticSearch service (all-in-one)
  - elastic.yaml

  # a test frontend
  - frontend.yaml

commonLabels:
  app: efkloganalysis
  environment: development