apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # FluentBit operator development version (https://github.com/fluent/fluentbit-operator)
  - https://raw.githubusercontent.com/fluent/fluentbit-operator/v0.12.0/manifests/setup/setup.yaml

  # some pods from quickstart example to test the operator
  - https://raw.githubusercontent.com/fluent/fluentbit-operator/v0.12.0/manifests/quick-start/quick-start.yaml

  # ElasticSearch service (all-in-one)
  #- elastic.yaml

  # a test frontend
  #- frontend.yaml

  # Kibana service
  #- kibana.yaml

commonLabels:
  environment: development