apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # FluentBit operator latest release (manifest directory download from https://github.com/fluent/fluentbit-operator/tree/v0.12.0)
  - fluentbit-operator-0.12.0/manifests/setup

  # logging
  - fluentbit-operator-0.12.0/manifests/logging-stack

  # ElasticSearch service (all-in-one)
  - elastic.yaml

  # Kibana service
  - kibana.yaml

  # a test frontend service exposed on 8080
  - frontend.yaml

commonLabels:
  environment: development