apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: kubesphere-logging-system
  labels:
    service: opensearch
spec:
  ports:
    - port: 9200
      name: client
    - port: 9300
      name: nodes
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: kubesphere-logging-system
spec:
  serviceName: "opensearch"
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:1.2.4
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: client
            - containerPort: 9300
              name: nodes
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: data
          emptyDir: {}
