apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: fluentd
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "false"
    logging.kubesphere.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  forward:
    host: fluentd.kubesphere-logging-system.svc
    port: 24224