apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  name: parser
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
spec:
  match: "*"
  filters:
  - parser:
      keyName: log
      parser: my-regex
