apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  service:
    # To use parser, you must enable parsersFile by setting its value to parsers.conf
    parsersFile: parsers.conf
  inputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
  filterSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
  outputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
  parserSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
